name: vaganza_news_app
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  provider: ^5.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.3
  google_fonts: ^2.0.0
  intl: ^0.17.0
  android_alarm_manager_plus: ^2.0.3
  flutter_local_notifications: ^5.0.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/articles.json
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
    - family: LibreFranklin
      fonts:
        - asset: assets/fonts/LibreFranklin-Regular.ttf
